"""Create games table

Revision ID: 69e6defddd6e
Revises: dde4f31d1da4
Create Date: 2025-06-14 22:13:12.829951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e6defddd6e'
down_revision: Union[str, None] = 'dde4f31d1da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.Column('treasury', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Integer(), nullable=False),
    sa.Column('military_strength', sa.Integer(), nullable=False),
    sa.Column('religious_influence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
