"""Add opening_brief to dynasty

Revision ID: d2c269fc1787
Revises: 1301d5c8111b
Create Date: 2025-06-14 22:59:29.585647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c269fc1787'
down_revision: Union[str, None] = '1301d5c8111b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynasties', sa.Column('opening_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dynasties', 'opening_brief')
    # ### end Alembic commands ###
