"""Add image_url to dynasty table

Revision ID: dde4f31d1da4
Revises: fd0f8b8b3c0e
Create Date: 2025-06-14 21:30:22.832095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde4f31d1da4'
down_revision: Union[str, None] = 'fd0f8b8b3c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynasties', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dynasties', 'image_url')
    # ### end Alembic commands ###
